# Generated by Django 5.0.6 on 2024-08-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0011_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='course_cart',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_cart',
            new_name='user',
        ),
    ]
