# Generated by Django 5.0.6 on 2024-08-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0012_rename_course_cart_cart_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
