# Generated by Django 5.0.6 on 2024-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0013_cart_slug_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='slug',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
